version: '3.8'

services:
  postgres:
    image: bitnami/postgresql
    container_name: intercom-postgres
    environment:
      POSTGRESQL_USERNAME: ${DB_USER}
      POSTGRESQL_PASSWORD: ${DB_PASSWORD}
      POSTGRESQL_DATABASE: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    networks:
      - app-network

  mosquitto:
    image: toke/mosquitto
    container_name: intercom-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - app-network

  app:
    build: .
    container_name: ufanet-intercom-service
    depends_on:
      - postgres
      - mosquitto
    ports:
      - "${APP_PORT}:8080"
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge